// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  styleBlock: string;
  workbenches: string;
}
declare const cssExports: CssExports;
export default cssExports;
