packages:
  # 选择 packages 目录下的所有首层子目录的包
  - packages/*
  - libs/*
  - cli/*
  - extensions/*
  - apps/*
  - src
  - .rd-cache
  - .rd-packer
  - templates/*


catalogs:
  packer:
    bytenode: "1.5.6"
    combined-stream: "1.0.8"
    crypto-ts: "1.0.2"
    delayed-stream: "1.0.0"
    follow-redirects: "1.15.6"
    form-data: "4.0.0"
    mime-db: "1.53.0"
    mime-types: "2.1.35"
    proxy-from-env: "1.1.0"
