// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  header: string;
  logo: string;
  menu: string;
  menuContainer: string;
}
declare const cssExports: CssExports;
export default cssExports;
