// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  didContent: string;
  login: string;
}
declare const cssExports: CssExports;
export default cssExports;
