// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bottomContainer: string;
  mainNavigationContainer: string;
  mainNavigationContainerPlaceholder: string;
  sideBarItem: string;
  topContainer: string;
}
declare const cssExports: CssExports;
export default cssExports;
