// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  mainContainer: string;
  mainRootContainer: string;
  workbenchesLayout: string;
}
declare const cssExports: CssExports;
export default cssExports;
