// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  rootRouteSwitchAppear: string;
  rootRouteSwitchAppearActive: string;
  rootRouteSwitchEnter: string;
  rootRouteSwitchEnterActive: string;
  rootRouteSwitchExit: string;
  rootRouteSwitchExitActive: string;
  workbenchesRouteSwitchAppear: string;
  workbenchesRouteSwitchAppearActive: string;
  workbenchesRouteSwitchEnter: string;
  workbenchesRouteSwitchEnterActive: string;
  workbenchesRouteSwitchExit: string;
  workbenchesRouteSwitchExitActive: string;
}
declare const cssExports: CssExports;
export default cssExports;
