// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  appRegion: string;
  appRegionNo: string;
  flex: string;
  flexAutoFit: string;
  flexCenter: string;
  flexCol: string;
  flexColCenter: string;
  flexColSpaceAround: string;
  flexColSpaceBetween: string;
  flexEnd: string;
  flexFixed: string;
  flexLeft: string;
  flexRight: string;
  flexSpaceAround: string;
  flexSpaceBetween: string;
  flexStart: string;
  fullSize: string;
  hFullSize: string;
  hidden: string;
  overflowHidden: string;
  overflowXHidden: string;
  overflowYHidden: string;
  userSelectNone: string;
  wFullSize: string;
}
declare const cssExports: CssExports;
export default cssExports;
