name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

#      - name: Run typecheck
#        run: pnpm typecheck
#
#      - name: Run tests
#        run: pnpm test:all

  cd:
    runs-on: ubuntu-latest
    steps:
#      - name: setup dist of website
#        run: pnpm website:build
#
#      - name: Deploy via rsync of website
#        uses: easingthemes/ssh-deploy@v2.1.6
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#          ARGS: "-rltgoDzvO"
#          SOURCE: "./dist/website"
#          REMOTE_HOST: ${{ secrets.SERVER_IP }}
#          REMOTE_USER: ${{ secrets.SERVER_USER }}
#          TARGET: "/www/wwwroot/oupro"  # 服务器目标路径

      - name: setup dist of rapid docs
        run: pnpm docs:build

      - name: Deploy via rsync of docs
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "./dist/docs"
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: "/www/wwwroot/docs"  # 服务器目标路径