name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

#      - name: Run typecheck
#        run: pnpm typecheck
#
#      - name: Run tests
#        run: pnpm test:all

  cd:
    runs-on: ubuntu-latest
    needs: ci  # 依赖 CI 任务完成
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'  # 核心条件
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm



      - name: Install dependencies
        run: pnpm install

      - name: setup dist of website
        run: pnpm website:build

      - name: Deploy via rsync of website
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
         SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
         ARGS: "-rltgoDzvO"
         SOURCE: "./dist/website/"
         REMOTE_HOST: ${{ secrets.SERVER_IP }}
         REMOTE_USER: ${{ secrets.SERVER_USER }}
         TARGET: "/www/wwwroot/oupro"  # 服务器目标路径

      - name: setup dist of rapid docs
        run: pnpm docs:build

      - name: Deploy via rsync of docs
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete --mkpath"
          SOURCE: "./dist/docs/"
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: "/www/wwwroot/rapid_doc/dist"  # 服务器目标路径
